GRAPHBOARD_SCALE = 0.4
PICTOGRAPH_SCALE = 0.2
ARROWBOX_SCALE = GRAPHBOARD_SCALE * 0.75



BETA_OFFSET = 25

GRAPHBOARD_HEIGHT = 900
GRAPHBOARD_WIDTH = 750
GRID_WIDTH = 650
GRID_PADDING = (GRAPHBOARD_HEIGHT - GRID_WIDTH) / 2

DISTANCE = 40

RATIO = 75 / 90

LETTER_ITEM_HEIGHT = 100

BUTTON_SIZE = 30
