GRAPHBOARD_SCALE = 0.5

STAFF_WIDTH = 25
STAFF_LENGTH = 250

DEFAULT_GRAPHBOARD_HEIGHT = 900
DEFAULT_GRAPHBOARD_WIDTH = 750
DEFAULT_GRID_WIDTH = 650

GRAPHBOARD_HEIGHT = DEFAULT_GRAPHBOARD_HEIGHT * GRAPHBOARD_SCALE
GRAPHBOARD_WIDTH = DEFAULT_GRAPHBOARD_WIDTH * GRAPHBOARD_SCALE

VERTICAL_OFFSET = (GRAPHBOARD_HEIGHT - GRAPHBOARD_WIDTH) / 2

GRID_WIDTH = 650 * GRAPHBOARD_SCALE
    
GRID_PADDING = ((GRAPHBOARD_WIDTH - GRID_WIDTH) / 2)

ARROW_DIR = 'images\\arrows'

ARROW_ADJUSTMENT_DISTANCE = 40 * GRAPHBOARD_SCALE

PICTOGRAPH_SCALE = 0.25
SELECTION_GRID_WIDTH = 650 * PICTOGRAPH_SCALE

RED = '#ed1c24'
BLUE = '#2e3192'

MINI_GRAPHBOARD_HEIGHT = 450
MINI_GRAPHBOARD_WIDTH = 375
MINI_GRID_WIDTH = 325
MINI_STAFF_WIDTH = 12.5
MINI_STAFF_LENGTH = 125
