GRAPHBOARD_SCALE = 0.5


STAFF_WIDTH = 25
STAFF_LENGTH = 250

GRAPHBOARD_HEIGHT = 900 * GRAPHBOARD_SCALE
GRAPHBOARD_WIDTH = 750 * GRAPHBOARD_SCALE

VERTICAL_OFFSET = (GRAPHBOARD_HEIGHT - GRAPHBOARD_WIDTH) / 2

GRID_WIDTH = 750 * GRAPHBOARD_SCALE
    
GRID_PADDING = ((GRAPHBOARD_WIDTH - GRID_WIDTH) / 2)

ARROW_ADJUSTMENT_DISTANCE = 40 * GRAPHBOARD_SCALE

PICTOGRAPH_SCALE = 0.5

RED = '#ed1c24'
BLUE = '#2e3192'

MINI_GRID_WIDTH = 325
MINI_STAFF_WIDTH = 12.5
MINI_STAFF_LENGTH = 125
