GRAPHBOARD_SCALE = 0.4
PICTOGRAPH_SCALE = 0.2
ARROWBOX_SCALE = GRAPHBOARD_SCALE * 0.75

MAIN_WINDOW_WIDTH = int(2600 * GRAPHBOARD_SCALE)
MAIN_WINDOW_HEIGHT = int(3000 * GRAPHBOARD_SCALE)

STAFF_WIDTH = 25
STAFF_LENGTH = 250

BETA_OFFSET = 20

GRAPHBOARD_HEIGHT = 900
GRAPHBOARD_WIDTH = 750
GRID_WIDTH = 650
GRID_PADDING = (GRAPHBOARD_HEIGHT - GRID_WIDTH) / 2

DISTANCE = 30

PICTOGRAPH_GRID_WIDTH = GRID_WIDTH * PICTOGRAPH_SCALE
PICTOGRAPH_WIDTH = int(GRAPHBOARD_WIDTH * PICTOGRAPH_SCALE)
PICTOGRAPH_HEIGHT = int(GRAPHBOARD_HEIGHT * PICTOGRAPH_SCALE)
PICTOGRAPH_GRID_PADDING = (PICTOGRAPH_WIDTH - PICTOGRAPH_GRID_WIDTH) / 2

INFOBOX_SIZE = 900 * GRAPHBOARD_SCALE

SEQUENCE_SCENE_WIDTH = 720
SEQUENCE_SCENE_HEIGHT = 720