
GRAPHBOARD_SCALE = 0.4
PICTOGRAPH_SCALE = 0.2
ARROWBOX_SCALE = GRAPHBOARD_SCALE * 0.75


STAFF_WIDTH = 25
STAFF_LENGTH = 250

BETA_OFFSET = 20

GRAPHBOARD_HEIGHT = 900
GRAPHBOARD_WIDTH = 750
GRID_WIDTH = 650
GRID_PADDING = (GRAPHBOARD_HEIGHT - GRID_WIDTH) / 2

DISTANCE = 30

LETTER_ITEM_HEIGHT = 100

INFOBOX_SIZE = 900 * GRAPHBOARD_SCALE



BUTTON_SIZE = 30